#!/usr/bin/env python3
"""Emit a Reid ``[globals]`` start TOML from a CANDEL per-galaxy init point.

Reads ``[model.galaxies.<GALAXY>.<variant>]`` from the selected dataset's
``init_<dataset>.toml`` (the same CANDEL starting point the blackjax sampler
uses; merged over ``config_maser.toml``), converts it to Reid's
20-global convention, and shifts the warp pivots to Reid's data-derived
``r_ref``.  The resulting TOML is consumable verbatim by
``run_reid_mcmc.py --init`` so Reid's fit_disk MCMC starts from *your* globals.

The Reid source is not touched; this only produces the start vector.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import tomli_w

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - py3.10 fallback
    import tomli as tomllib

from .run_reid_mcmc import (DEFAULT_CONFIG, GLOBAL_NAMES, SCRIPT_DIR,
                            add_dataset_arg, compute_reid_r_ref,
                            load_config_init, load_toml, parse_data_rows,
                            reid_data_path, resolve_dataset,
                            shift_warp_pivots)

HEADER = (
    "# Reid fit_disk start globals, generated by make_candel_globals.py from\n"
    "# CANDEL's per-dataset init points. One\n"
    "# [globals.<GALAXY>.<variant>] table per galaxy/variant; consumed by\n"
    "# run_reid_mcmc.py --init mystart_globals_<dataset>.toml --galaxy\n"
    "# <GALAXY> --variant <variant>.\n\n"
)


def default_out(dataset):
    name = ("mystart_globals.toml" if dataset == "original_published" else
            f"mystart_globals_{dataset}.toml")
    return SCRIPT_DIR / name


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--galaxy", required=True)
    p.add_argument("--variant", default="init", choices=["init", "init_qw"])
    p.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    add_dataset_arg(p)
    p.add_argument(
        "--data",
        type=Path,
        default=None,
        help="Reid-format data file (defaults to "
             "data/Megamaser/<dataset>/<GALAXY>_loader_reid.inp). Must match "
             "the --data passed to run_reid_mcmc.py so r_ref is consistent.",
    )
    p.add_argument("--vcor", type=float, default=0.0)
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Merged globals TOML to update in place "
             "(default: legacy mystart_globals.toml for original_published; "
             "otherwise mystart_globals_<dataset>.toml).",
    )
    args = p.parse_args(argv)

    dataset = resolve_dataset(load_toml(args.config), args.dataset)
    data = args.data or reid_data_path(args.galaxy, dataset)
    out = args.out or default_out(dataset)
    if not data.exists():
        p.error(
            f"Reid data file not found: {data}\n"
            f"Run: python prepare_reid_data.py {args.galaxy} "
            f"--dataset {dataset}")

    reid_init = load_config_init(
        args.config, args.galaxy, args.vcor, variant=args.variant,
        dataset=dataset)
    header, rows = parse_data_rows(data)
    reid_r_ref = compute_reid_r_ref(rows, header, reid_init.values)
    g = shift_warp_pivots(reid_init.values, reid_r_ref)

    entry = {
        "source": f"init_{dataset}.toml "
                  f"[model.galaxies.{args.galaxy}.{args.variant}]",
        "dataset": dataset,
        "r_ref_mas": reid_r_ref,
        "r_ref_data": data.name,
    }
    entry.update({name: g[name] for name in GLOBAL_NAMES})

    cfg = tomllib.loads(out.read_text()) if out.exists() else {}
    galaxies = cfg.setdefault("globals", {})
    galaxies.setdefault(args.galaxy, {})[args.variant] = entry
    cfg["globals"] = {
        gal: {
            v: galaxies[gal][v]
            for v in sorted(galaxies[gal], key=lambda v: (v != "init", v))
        }
        for gal in sorted(galaxies)
    }
    out.write_text(HEADER + tomli_w.dumps(cfg))
    print(f"Wrote {out} [globals.{args.galaxy}.{args.variant}] "
          f"(r_ref = {reid_r_ref:.6f} mas)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
