#!/bin/bash -l
# Submit the fit_disk_Reid_reflection variant comparison to the cluster,
# ONE JOB PER VARIANT (reid_original / eta_reparam / eta_gibbs /
# eta_gibbs_reflection, or a --variants subset), each requesting one CPU
# core per chain. reid_original is Reid's true original formulation (joint
# sampler AND flat-(H0,M) coordinates; ignores --eta/--no-eta). All variant
# jobs share one --out-dir, and a small dependent collect job is auto-queued
# (scheduler --runafter) to compute the R-hat table, the numpyro summaries,
# and the CANDEL/Reid overlay plots via run_gibbs_comparison.py --skip-run once
# all variant jobs finish. Use --no-collect to skip it, or --collect --out-dir
# D to (re)run collection manually.
#
# Reid's Fortran code is not internally parallel, so each variant job runs
# --chains independent one-strand processes (see run_gibbs_chains.sh) on its
# reserved cores.
#
# NOTE: background_info/fit_disk_Reid_reflection/ (the modified Reid Fortran)
# is deliberately untracked; rsync it to the cluster checkout before
# submitting. The Reid data file data/Megamaser/<dataset>/<gal>_loader_reid.inp
# is auto-generated by the runner if missing.
set -euo pipefail

PKG_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Core CANDEL checkout (_submit_lib.sh, local_config.toml); defaults
# to a sibling clone of candel-cosmo/CANDEL.
ROOT="${CANDEL_ROOT:-$(cd "$PKG_ROOT/../candel" 2>/dev/null && pwd)}"
[[ -f "$ROOT/scripts/_submit_lib.sh" ]] || {
    echo "[ERROR] Set CANDEL_ROOT to the CANDEL core checkout." >&2; exit 1; }
# shellcheck source=../../../../scripts/_submit_lib.sh
source "$ROOT/scripts/_submit_lib.sh"

THIS="$PKG_ROOT/scripts/reid/submit_gibbs_comparison.sh"
RUNNER="candel_maser.reid.run_gibbs_comparison"

ALL_VARIANTS="reid_original,eta_reparam,eta_gibbs,eta_gibbs_reflection"

QUEUE=""
GALAXY="NGC6323"
DATASET=""
CHAINS=4
MEM_PER_CHAIN=7
CONTROL_TEMPLATE=""
DATA=""
CANDEL_HDF5=""
BASE_OUTPUT="$CANDEL_ROOT_RESULTS/results/Megamaser/reid_mcmc"
OUT_DIR=""
WARMUP=1000000
SAMPLES=1000000
SEED=47351937
N_INNER=20
WRITE_THIN=10
ETA=true
INIT=config
H0_RANGE=""
VARIANTS="all"
MATCH_PRIORS="T"
REWEIGHT_DA2=false
COLLECT=false
AUTO_COLLECT=true
CHAINS_ONLY=false
DRY=false
WORKER=false

usage() {
    cat <<EOF
Usage: bash $0 -q QUEUE [options]              # one chain job per variant
       bash $0 -q QUEUE --collect --out-dir D  # R-hat + plots once done

Submits fit_disk_Reid_reflection variants (reid_original = Reid's true
original formulation, always eta-off; eta_reparam, eta_gibbs,
eta_gibbs_reflection -- all four or a --variants subset) as ONE JOB PER
VARIANT, each
running --chains parallel one-core chains into a shared --out-dir. A small
collect job (Gelman-Rubin R-hat table + CANDEL/Reid overlay plots) is
auto-queued with a scheduler dependency on the variant jobs, so it runs
itself once they all finish -- no need to rerun with --out-dir.

Required:
  -q, --queue QUEUE          Queue/partition (cluster=$CANDEL_CLUSTER)

Options:
  -n, --chains, --cpus N     Chains per variant / CPU cores per variant job
                             (default: $CHAINS; one chain per CPU)
  --mem-per-chain GB         Memory per chain/CPU in GB (default: $MEM_PER_CHAIN)
  --galaxy NAME              Galaxy name (default: $GALAXY)
  --dataset NAME             Spot-table dataset (default: config [io].dataset)
  --control-template PATH    fit_disk_control.inp with this galaxy's priors
                             (default: the selected dataset's control)
  --data PATH                Reid-format maser data file (default:
                             data/Megamaser/<dataset>/<galaxy>_loader_reid.inp,
                             auto-generated by the runner if missing)
  --candel PATH              CANDEL posterior HDF5 for the overlay corner
                             (used by --collect only)
  --output-dir DIR           Batch output directory root
                             (default: $BASE_OUTPUT)
  --out-dir DIR              Exact shared output directory (default:
                             timestamped dir under --output-dir); REQUIRED
                             for --collect
  --num-warmup N             Primary burn-in trials (default: $WARMUP)
  --num-samples N            Production trials per chain (default: $SAMPLES)
  --seed N                   Seed for chain 0 (default: $SEED)
  --n-inner N                Per-spot latent sweeps per Gibbs iteration
                             (default: $N_INNER)
  --write-thin N             Write only every Nth stored sample to
                             fort.7/fort.74, shrinking the chain files
                             and the collect step's parse time (the
                             in-Fortran Ho-M bootstrap still sees every
                             stored sample) (default: $WRITE_THIN)
  --eta / --no-eta           Reparameterize the BH mass as eta =
                             log10(Mbh/D_A) with a measure flat in
                             (D_A, eta) (CANDEL's coordinates); applies
                             to all selected variants (default: on;
                             --no-eta for Reid's original flat-(H0,M)
                             sampling)
  --variants LIST            Comma-separated subset of
                             $ALL_VARIANTS (default: all)
  --init config|pesce        Chain start point: config (control-template
                             value column, CANDEL globals) or pesce
                             (published Pesce/Reid disk point) (default: config)
  --H0-range LOW,HIGH        Restrict the Ho sampling window: overwrites the
                             control file's Initial-Ho-strand-range line.
                             Reid's Fortran expands this by +-10 km/s for
                             the actual hard prior bound, so the true
                             enforced range is [LOW-10, HIGH+10] (default:
                             unset, control template's own window)
  --match-priors T|F|orig    Error-floor treatment for ALL variants (default:
                             T): T=CANDEL Gaussian floors (SAMPLED, Pesce-
                             style); F=template floors verbatim; orig=original
                             Reid/Kuo fixed floors (NOT sampled; Kuo 2015 /
                             Reid 2013 reproduction)
  --collect                  Submit the aggregation job (R-hat, summaries,
                             plots) instead of chain jobs
  --no-collect               Do NOT auto-queue the dependent collect job
                             after the variant jobs (submit chains only)
  --reweight-da2             D_A^2-reweight the Reid chains in the plots
                             (collect step)
  --dry                      Print submit commands without submitting
  -h, --help
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --worker) WORKER=true; shift ;;
        --chains-only) CHAINS_ONLY=true; shift ;;
        --collect) COLLECT=true; shift ;;
        --no-collect) AUTO_COLLECT=false; shift ;;
        -q|--queue) QUEUE="$2"; shift 2 ;;
        -n|--chains|--cpus) CHAINS="$2"; shift 2 ;;
        --mem-per-chain) MEM_PER_CHAIN="$2"; shift 2 ;;
        --galaxy) GALAXY="$2"; shift 2 ;;
        --dataset) DATASET="$2"; shift 2 ;;
        --control-template) CONTROL_TEMPLATE="$2"; shift 2 ;;
        --data) DATA="$2"; shift 2 ;;
        --candel) CANDEL_HDF5="$2"; shift 2 ;;
        --output-dir) BASE_OUTPUT="$2"; shift 2 ;;
        --out-dir) OUT_DIR="$2"; shift 2 ;;
        --num-warmup) WARMUP="$2"; shift 2 ;;
        --num-samples) SAMPLES="$2"; shift 2 ;;
        --seed) SEED="$2"; shift 2 ;;
        --n-inner) N_INNER="$2"; shift 2 ;;
        --write-thin) WRITE_THIN="$2"; shift 2 ;;
        --eta) ETA=true; shift ;;
        --no-eta) ETA=false; shift ;;
        --init) INIT="$2"; shift 2 ;;
        --H0-range) H0_RANGE="$2"; shift 2 ;;
        --variants) VARIANTS="$2"; shift 2 ;;
        --reweight-da2) REWEIGHT_DA2=true; shift ;;
        --match-priors) MATCH_PRIORS="$2"; shift 2 ;;
        --dry) DRY=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

if [[ "$CHAINS" -lt 1 ]]; then
    echo "[ERROR] --chains must be >=1"; exit 1
fi
if [[ -n "$DATASET" && "$DATASET" != "original_published" && "$DATASET" != "fiducial" ]]; then
    echo "[ERROR] --dataset must be original_published or fiducial"; exit 1
fi
[[ "$MATCH_PRIORS" =~ ^(T|F|orig)$ ]] || { echo "[ERROR] --match-priors must be T, F, or orig, got: $MATCH_PRIORS"; exit 1; }

# Floor-mode tag embedded in job names (=> logs-<jobid>-<name>.out), matching
# the run_gibbs_comparison artifact tags, so an orig/F run does not collide
# with a default-T run of the same galaxy/init.
case "$MATCH_PRIORS" in
    orig) MP_TAG="_origfloor" ;;
    F)    MP_TAG="_flatfloor" ;;
    *)    MP_TAG="" ;;
esac

[[ "$VARIANTS" == "all" ]] && VARIANTS="$ALL_VARIANTS"
IFS=',' read -ra VLIST <<< "$VARIANTS"
for v in "${VLIST[@]}"; do
    case ",$ALL_VARIANTS," in
        *",$v,"*) ;;
        *) echo "[ERROR] unknown variant '$v' (choose from $ALL_VARIANTS)"; exit 1 ;;
    esac
done

if [[ -z "$OUT_DIR" ]]; then
    if $COLLECT; then
        echo "[ERROR] --collect needs --out-dir (the chain jobs' shared dir)"
        exit 1
    fi
    stamp="$(date +%Y%m%d_%H%M%S)"
    OUT_DIR="$BASE_OUTPUT/gibbs_comparison_${GALAXY}_${CHAINS}chains_${stamp}"
fi

# ----------------------------------------------------------------------
# Worker: runs on the compute node. Chain jobs pass a single variant plus
# --chains-only; the collect job passes the full list plus --collect.
if $WORKER; then
    mkdir -p "$OUT_DIR"
    echo "Running Gibbs comparison worker on $(hostname)"
    echo "  out_dir=$OUT_DIR"
    echo "  galaxy=$GALAXY, variants=$VARIANTS, chains=$CHAINS"
    echo "  warmup=$WARMUP, samples=$SAMPLES, n_inner=$N_INNER, write_thin=$WRITE_THIN"

    cmd=(
        "$CANDEL_PYTHON" -u -m "$RUNNER"
        --galaxy "$GALAXY"
        --out-dir "$OUT_DIR"
        --chains "$CHAINS"
        --num-warmup "$WARMUP"
        --num-samples "$SAMPLES"
        --seed "$SEED"
        --n-inner "$N_INNER"
        --write-thin "$WRITE_THIN"
        --match-priors "$MATCH_PRIORS"
        --variants "$VARIANTS"
    )
    [[ -n "$DATASET" ]] && cmd+=(--dataset "$DATASET")
    $CHAINS_ONLY && cmd+=(--chains-only)
    $COLLECT && cmd+=(--skip-run)
    if $ETA; then cmd+=(--eta); else cmd+=(--no-eta); fi
    cmd+=(--init "$INIT")
    [[ -n "$H0_RANGE" ]] && cmd+=(--H0-range "$H0_RANGE")
    $REWEIGHT_DA2 && cmd+=(--reweight-da2)
    [[ -n "$CONTROL_TEMPLATE" ]] && cmd+=(--control-template "$CONTROL_TEMPLATE")
    [[ -n "$DATA" ]] && cmd+=(--data "$DATA")
    [[ -n "$CANDEL_HDF5" ]] && cmd+=(--candel "$CANDEL_HDF5")

    tag="collect"
    $CHAINS_ONLY && tag="${VARIANTS//,/_}"
    printf "%s\n" "${cmd[*]}" > "$OUT_DIR/command_${tag}.txt"
    "${cmd[@]}"
    exit 0
fi

if [[ -z "$QUEUE" ]]; then
    echo "[ERROR] -q QUEUE is required (cluster=$CANDEL_CLUSTER)"; exit 1
fi

# Common worker argument tail forwarded to every submitted job.
worker_tail=(
    --queue "$QUEUE"
    --galaxy "$GALAXY"
    --output-dir "$BASE_OUTPUT"
    --out-dir "$OUT_DIR"
    --num-warmup "$WARMUP"
    --num-samples "$SAMPLES"
    --seed "$SEED"
    --n-inner "$N_INNER"
    --write-thin "$WRITE_THIN"
    --init "$INIT"
    --match-priors "$MATCH_PRIORS"
)
[[ -n "$DATASET" ]] && worker_tail+=(--dataset "$DATASET")
[[ -n "$H0_RANGE" ]] && worker_tail+=(--H0-range "$H0_RANGE")
if $ETA; then worker_tail+=(--eta); else worker_tail+=(--no-eta); fi
$REWEIGHT_DA2 && worker_tail+=(--reweight-da2)
[[ -n "$CONTROL_TEMPLATE" ]] && worker_tail+=(--control-template "$CONTROL_TEMPLATE")
[[ -n "$DATA" ]] && worker_tail+=(--data "$DATA")
[[ -n "$CANDEL_HDF5" ]] && worker_tail+=(--candel "$CANDEL_HDF5")

# ----------------------------------------------------------------------
# Collect: one small job for R-hat + summaries + plots (parses every
# chain's fort.7, so give it a couple of cores' worth of memory). $1, if
# given, is a colon-joined list of variant job IDs to wait on (--runafter).
submit_collect() {
    local dep="${1:-}"
    local cmd=(/bin/bash "$THIS" --worker --collect
               --variants "$VARIANTS" --chains "$CHAINS" "${worker_tail[@]}")
    local submit_args=(--queue "$QUEUE" --mem 8 --cpus 2 --name "gibbscol_${GALAXY}_${INIT}${MP_TAG}")
    [[ -n "$dep" ]] && submit_args+=(--runafter "$dep")
    $DRY && submit_args+=(--dry)
    submit_job "${submit_args[@]}" -- "${cmd[@]}"
}

if $COLLECT; then
    echo "Submitting Gibbs-comparison COLLECT -> $CANDEL_CLUSTER:$QUEUE"
    echo "  variants: $VARIANTS"
    echo "  out_dir:  $OUT_DIR"
    submit_collect
    exit 0
fi

# ----------------------------------------------------------------------
# Default: one chain job per variant, all writing into the shared OUT_DIR.
MEM_TOTAL=$((CHAINS * MEM_PER_CHAIN))
echo "Submitting Gibbs comparison -> $CANDEL_CLUSTER:$QUEUE"
echo "  variants:        $VARIANTS (one job each, n_inner=$N_INNER, write_thin=$WRITE_THIN)"
echo "  chains/CPUs:     $CHAINS per variant job"
echo "  memory:          ${MEM_TOTAL} GB per job (${MEM_PER_CHAIN} GB per chain)"
echo "  warmup/samples:  $WARMUP / $SAMPLES"
echo "  galaxy:          $GALAXY"
echo "  dataset:         ${DATASET:-config default}"
echo "  out_dir:         $OUT_DIR"

$DRY || mkdir -p "$OUT_DIR"

job_ids=()
for v in "${VLIST[@]}"; do
    JOB_NAME="gibbs_${v}_${GALAXY}_${INIT}${MP_TAG}"
    cmd=(/bin/bash "$THIS" --worker --chains-only
         --variants "$v" --chains "$CHAINS" "${worker_tail[@]}")
    submit_args=(--queue "$QUEUE" --mem "$MEM_PER_CHAIN" --cpus "$CHAINS"
                 --name "$JOB_NAME")
    $DRY && submit_args+=(--dry)
    submit_out="$(submit_job "${submit_args[@]}" -- "${cmd[@]}")"
    echo "$submit_out"
    jid="$(printf '%s\n' "$submit_out" | grep -oP 'JOBID=\K[0-9]+' | tail -n1 || true)"
    [[ -n "$jid" ]] && job_ids+=("$jid")
done

echo
if ! $AUTO_COLLECT; then
    echo "Once ALL variant jobs have finished, collect with:"
    echo "  bash $THIS -q $QUEUE --collect --out-dir $OUT_DIR --variants $VARIANTS --galaxy $GALAXY${DATASET:+ --dataset $DATASET}"
elif $DRY; then
    echo "[dry] collect job would be auto-queued with --runafter on the variant jobs:"
    submit_collect
else
    if [[ "${#job_ids[@]}" -ne "${#VLIST[@]}" ]]; then
        echo "[ERROR] expected ${#VLIST[@]} variant job IDs, got ${#job_ids[@]};" >&2
        echo "        collect NOT queued. Once all variant jobs finish, run:" >&2
        echo "  bash $THIS -q $QUEUE --collect --out-dir $OUT_DIR --variants $VARIANTS --galaxy $GALAXY${DATASET:+ --dataset $DATASET}" >&2
        exit 1
    fi
    deps="$(IFS=:; echo "${job_ids[*]}")"
    echo "Auto-queuing collect job to run after variant jobs [$deps]..."
    submit_collect "$deps"
fi
